# Generated by hand for TanPit A07 dual-sign drain

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pits", "0001_initial"),
    ]
    operations = [
        migrations.CreateModel(
            name="SignBook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("opened_by", models.CharField(max_length=64)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_by", models.CharField(blank=True, max_length=64)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="pits.pit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Signature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("signer", models.CharField(max_length=64)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_by", models.CharField(blank=True, max_length=64)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="pits.signbook",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="signbook",
            constraint=models.UniqueConstraint(
                fields=("pit",),
                condition=models.Q(("withdrawn_at__isnull", True)),
                name="uniq_active_book_per_pit",
            ),
        ),
        migrations.AddConstraint(
            model_name="signature",
            constraint=models.UniqueConstraint(
                fields=("book", "signer"),
                condition=models.Q(("revoked_at__isnull", True)),
                name="uniq_active_signature_per_book_person",
            ),
        ),
    ]
