# Generated by hand for TanPit co-sign book

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pits", "0001_initial"),
    ]
    operations = [
        migrations.CreateModel(
            name="SignBook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created_by", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_by", models.CharField(blank=True, max_length=64)),
                (
                    "pit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sign_books",
                        to="pits.pit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Signature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("signer", models.CharField(max_length=64)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_by", models.CharField(blank=True, max_length=64)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="pits.signbook",
                    ),
                ),
                (
                    "pit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="pits.pit",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="signbook",
            constraint=models.UniqueConstraint(
                condition=models.Q(("withdrawn_at__isnull", True)),
                fields=("pit",),
                name="uniq_active_book_per_pit",
            ),
        ),
        migrations.AddConstraint(
            model_name="signature",
            constraint=models.UniqueConstraint(
                condition=models.Q(("withdrawn_at__isnull", True)),
                fields=("pit", "signer"),
                name="uniq_active_signature_per_pit_signer",
            ),
        ),
    ]
